-- Slice 106: Content Planning with Jumbo
-- Users co-create a content plan with Jumbo; approved plans are executed by the VPS runner.

-- 1. content_plans table ──────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS content_plans (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  brand_id        UUID        NOT NULL,
  items           JSONB       NOT NULL DEFAULT '[]',  -- [{topic, angle, format}]
  status          TEXT        NOT NULL DEFAULT 'draft',
    -- draft | approved | executing | done | failed
  approved_at     TIMESTAMPTZ,
  last_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE content_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users see own content plans"
  ON content_plans FOR ALL
  USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS content_plans_brand_status
  ON content_plans(brand_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS content_plans_user_approved
  ON content_plans(user_id, status, approved_at ASC)
  WHERE status = 'approved';

-- 2. Add source column to agent_deliverables ──────────────────────────────────
-- Lets the approval queue show whether a post came from the autonomous pipeline
-- or from a user-approved content plan.

ALTER TABLE agent_deliverables
  ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'autonomous';
  -- Values: 'autonomous' | 'planned'

COMMENT ON COLUMN agent_deliverables.source IS
  'autonomous = generated by the VPS cron pipeline; planned = generated from a user-approved content plan';
