#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────
# OpenClaw VPS Setup Script — PositionedUp Agent Squad
# Run this on your Hostinger VPS after SSH-ing in as root
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/YOUR_REPO/deploy/setup-vps.sh | bash
#   OR
#   scp deploy/setup-vps.sh root@YOUR_VPS_IP:~/setup-vps.sh
#   ssh root@YOUR_VPS_IP 'bash ~/setup-vps.sh'
# ─────────────────────────────────────────────────────────

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log()   { echo -e "${GREEN}[+]${NC} $1"; }
warn()  { echo -e "${YELLOW}[!]${NC} $1"; }
error() { echo -e "${RED}[x]${NC} $1"; }
info()  { echo -e "${BLUE}[i]${NC} $1"; }

# ── Step 1: System Update ────────────────────────────────
log "Step 1/7: Updating system packages..."
apt-get update -qq
apt-get upgrade -y -qq
apt-get install -y -qq git curl ca-certificates ufw fail2ban

# ── Step 2: Install Docker ────────────────────────────────
if command -v docker &>/dev/null; then
    log "Docker already installed: $(docker --version)"
else
    log "Step 2/7: Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
    log "Docker installed: $(docker --version)"
fi

# Verify Docker Compose
if docker compose version &>/dev/null; then
    log "Docker Compose: $(docker compose version)"
else
    error "Docker Compose not found. Install manually."
    exit 1
fi

# ── Step 3: Security Hardening ────────────────────────────
log "Step 3/7: Configuring firewall (UFW)..."
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
# Do NOT open port 18789 publicly. Access via SSH tunnel only.
ufw --force enable
log "Firewall configured. Only SSH (22) is open."

# Enable fail2ban for SSH brute force protection
systemctl enable fail2ban
systemctl start fail2ban
log "Fail2ban enabled for SSH protection."

# ── Step 4: Create project directory ──────────────────────
DEPLOY_DIR="/opt/openclaw"
log "Step 4/7: Setting up project directory at $DEPLOY_DIR..."
mkdir -p "$DEPLOY_DIR"
cd "$DEPLOY_DIR"

# ── Step 5: Create persistent directories ─────────────────
log "Step 5/7: Creating persistent directories..."
mkdir -p /var/openclaw/config
mkdir -p /var/openclaw/workspace
mkdir -p /var/openclaw/workspace/drafts
mkdir -p /var/openclaw/workspace/assets
mkdir -p /var/openclaw/workspace/archive
mkdir -p /var/openclaw/workspace/research
chown -R 1000:1000 /var/openclaw

# ── Step 6: Generate secrets ──────────────────────────────
log "Step 6/9: Generating security tokens..."
GATEWAY_TOKEN=$(openssl rand -hex 32)
AGENT_API_KEY=$(openssl rand -hex 32)
info "Gateway token:  $GATEWAY_TOKEN"
info "Agent API key:  $AGENT_API_KEY"

# ── Step 7: SSH Hardening ────────────────────────────────
log "Step 7/9: Hardening SSH..."
SSH_CONFIG="/etc/ssh/sshd_config"

# Disable root password auth if key auth is available
if [ -f /root/.ssh/authorized_keys ] && [ -s /root/.ssh/authorized_keys ]; then
    # Only modify if not already set
    if ! grep -q "^PasswordAuthentication no" "$SSH_CONFIG" 2>/dev/null; then
        warn "SSH key detected. Consider disabling password auth:"
        info "  echo 'PasswordAuthentication no' >> $SSH_CONFIG && systemctl restart sshd"
    fi
fi

# Disable empty passwords
if ! grep -q "^PermitEmptyPasswords no" "$SSH_CONFIG" 2>/dev/null; then
    echo "PermitEmptyPasswords no" >> "$SSH_CONFIG"
fi

# Max auth retries
if ! grep -q "^MaxAuthTries" "$SSH_CONFIG" 2>/dev/null; then
    echo "MaxAuthTries 3" >> "$SSH_CONFIG"
fi

systemctl restart sshd 2>/dev/null || true
log "SSH hardened."

# ── Step 8: Create .env template ─────────────────────────
log "Step 8/9: Creating .env template..."
ENV_FILE="$DEPLOY_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
    cat > "$ENV_FILE" << ENVEOF
# ── Generated by setup-vps.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ") ──
OPENCLAW_GATEWAY_TOKEN=$GATEWAY_TOKEN
AGENT_API_KEY=$AGENT_API_KEY

# ── LLM Provider ──
OPENAI_API_KEY=sk-PASTE_YOUR_KEY_HERE

# ── Telegram (run: bash deploy/telegram-setup.sh) ──
TELEGRAM_BOT_TOKEN=PASTE_BOT_TOKEN_HERE
TELEGRAM_OWNER_CHAT_ID=PASTE_CHAT_ID_HERE

# ── Brain API Connection ──
POSITIONEDUP_API_URL=https://your-api.vercel.app
POSITIONEDUP_USER_ID=your-supabase-user-id

# ── Optional ──
# POSTHOG_API_KEY=
# POSTHOG_HOST=https://us.i.posthog.com
# GOOGLE_ACCESS_TOKEN=
# OPENCLAW_DOMAIN=agents.positionedup.com
# ACME_EMAIL=admin@positionedup.com
ENVEOF
    log "Created $ENV_FILE — edit it with your actual values"
else
    warn ".env already exists at $ENV_FILE — skipping"
fi

# ── Step 9: Summary ──────────────────────────────────────
log "Step 9/9: Setup complete!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}VPS is ready for OpenClaw deployment!${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Generated secrets (saved to $ENV_FILE):"
echo -e "  Gateway Token: ${YELLOW}$GATEWAY_TOKEN${NC}"
echo -e "  Agent API Key: ${YELLOW}$AGENT_API_KEY${NC}"
echo ""
echo "Next steps:"
echo "  1. Clone your repo:  git clone YOUR_REPO_URL $DEPLOY_DIR/app"
echo "  2. Edit .env:        nano $DEPLOY_DIR/.env"
echo "  3. Setup Telegram:   bash $DEPLOY_DIR/app/deploy/telegram-setup.sh"
echo "  4. Copy env + build:"
echo "       cd $DEPLOY_DIR/app"
echo "       cp $DEPLOY_DIR/.env deploy/.env"
echo "       docker compose -f deploy/docker-compose.yml up -d --build"
echo "  5. Verify:           bash deploy/verify-deployment.sh"
echo "  6. Check logs:       docker compose -f deploy/docker-compose.yml logs -f"
echo ""
echo "Access options:"
echo "  A) SSH tunnel (most secure):"
echo "     ssh -N -L 18789:127.0.0.1:18789 root@YOUR_VPS_IP"
echo "     Open: http://127.0.0.1:18789"
echo ""
echo "  B) HTTPS with Caddy (requires domain pointed to VPS):"
echo "     Set OPENCLAW_DOMAIN in .env"
echo "     ufw allow 80 && ufw allow 443"
echo "     docker compose -f deploy/docker-compose.yml --profile https up -d"
echo ""
echo -e "  ${YELLOW}IMPORTANT: Copy Agent API Key to your Vercel backend env vars too!${NC}"
echo "  The AGENT_API_KEY must match in both places."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
